## Support for Arm64-based lambdas when downloading packages requiring native binaries. Such as Sharp.
supportedArchitectures:
  os:
    - 'current'
    - 'linux'
  cpu:
    - 'current'
    - 'arm64'
